#数据库设置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dormitory?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 3333
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  #实体类地址
  type-aliases-package: com.sakura.dormitory.pojo
  mapper-locations: classpath:mapper/*.xml

    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
#    druid:
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,log4j,config
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;
#
#
#
#logging:
#  level:
#    ROOT: INFO
#    org.springframework: INFO
#    java.sql.Connection: DEBUG
#    java.sql.Statement: DEBUG
#    org.apache: INFO
#    org.mongodb.driver: INFO
#    com.dmc: DEBUG

#停止spring boot 应用请post  http://localhost:8080/actuator/shutdown
management:
  endpoints:
    web:
      exposure:
        include: shutdown
    #注意下面这个位置！！
  endpoint:
    shutdown:
      enabled: true

